### ISSUE TITLE
App not offered for install on iOS

### ISSUE THREAD

**Issue by Marcoevich** [GoogleChromeLabs/pwa-wp#208]
Hi All,

Have done some tests using your plugin with our website https://louterbloemen.nl. First with current stable version 0.2 and now running 0.3b1 from source. During our tests we noticed that the app is not offered for install on iOS, be it Safari, Firefox or Chrome.

Can we fix this before the new release? I can help to debug this issue.

**Comment by westonruter** [comment]
Sure thing. 

Could it be that you don't have a site icon configured in the Customizer? I believe Safari required the apple-touch-icon in addition to the icon in the Web App Manifest.

**Comment by westonruter** [comment]
See #118 fixed by #129.

**Comment by Marcoevich** [comment]
Thanks Westion, I had indeed not set a site icon in the customizer, but after adding one and clearing cache I still do not get an offer to install the app.

I check #118. I know OP aristath, he's a developer of the theme that I use for the site.

**Comment by westonruter** [comment]
@Marcoevich I ran a Lighthouse audit for your site and the results show:

![image](https://user-images.githubusercontent.com/134745/62492086-7c446780-b782-11e9-92ca-72054c8deaca.png)

There is no service worker being installed at all.

![image](https://user-images.githubusercontent.com/134745/62492166-a85fe880-b782-11e9-9258-874a7665e727.png)

I don't think the PWA plugin is active?

**Comment by westonruter** [comment]
I don't see a reason to hold up the v0.3 of the plugin.

**Comment by Marcoevich** [comment]
I had the plugin running from source, I guess that didn't work correctly because my grunt build failed. I've installed 0.2 stable now, issue is the same with that one.

I'll wait for your 0.3 release and test again, if the issue persists I'll reopen this.

**Comment by Marcoevich** [comment]
Hello Weston,

I've tested this now with the 3.0 release. The app is now offered for install on Chrome Desktop, but still not on any iOS browser.

I've done the Lighthouse audit myself now, these are the results:

![image](https://user-images.githubusercontent.com/1243033/62611348-abcfad00-b905-11e9-8a1e-a046dfdb879d.png)

**Comment by westonruter** [comment]
Is this just an issue that iOS just doesn't support install prompts? See https://github.com/xwp/pwa-wp/issues/185
